---
abstract: 'Install the Graph::Writer modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Graph-Writer
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Graph::Graph6: 4
  Graph::Writer: 2.07
  Graph::Writer::Cytoscape: 1
  Graph::Writer::DSM: 0.06
  Graph::Writer::DrGeo: 0.01
  Graph::Writer::GraphViz: 0.11
  Graph::Writer::TGXML: 0.01
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Graph-Writer
  homepage: https://github.com/tupinek/Task-Graph-Writer
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-Graph-Writer
version: '0.02'
